
meta_product_name: "Clean my Footprint"
meta_title: "Clean my Footprint - Calculate and clean your carbon footprint"
meta_description: "You can clean the carbon footprint of your trips by making donations to associations"
meta_image: "rails-photo.jpg"                           # Une image dans votre dossier app/assets/images/
twitter_account: "@nomdevotrecompte"              # indispensable pour les Twitter Cards
